version: "3"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
    - postgres
    tty: true
    stdin_open: true
  app:
    build: ./app
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
      - ./app:/app
    ports:
      - "4200:4200"
    depends_on:
      - api