---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/ativos/{nome_ativo}":
    parameters:
    - name: nome_ativo
      in: path
      description: nome_ativo
      required: true
      schema:
        type: string
    get:
      summary: list ativos
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
